template_path: remote/jumpcloud.yaml
stack_name: jumpcloud
dependencies:
  - prod/essentials.yaml
parameters:
  LambdaBucket: essentials-awss3lambdaartifactsbucket-x29ftznj6pqw
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/jumpcloud.yaml --create-dirs -o templates/remote/jumpcloud.yaml"
