template_path: VPCPeer.yaml
stack_name: peering-stridespoolvpc
parameters:
  PeerVPC: vpc-0e9b80dc470a797d5  # stridespoolvpc IDD
  PeerVPCOwner: "423819316185"    # org-sagebase-strides account ID
  PeerVPCCIDR: 10.49.0.0/16       # stridespoolvpc CIDR
  PeerRoleName: essentials-VPCPeeringAuthorizerRole-CVZEDVMU5NZX   # org-sagebase-strides us-east-1-essentials-VPCPeeringAuthorizerRole
