template_path: templates/VPCPeer.yaml
stack_name: peering-computevpc-base
parameters:
  PeerVPC: vpc-78436103
  PeerVPCOwner: "{{ environment_variable.SciCompAwsAccountId }}"
  PeerVPCCIDR: 10.15.0.0/16
  PeerRoleName: essentials-VPCPeeringAuthorizerRole-19X5D81TAK34F
