template_path: templates/VPCPeer.yaml
stack_name: peering-synapsedev
parameters:
  PeerVPC: vpc-1362e468
  PeerVPCOwner: "{{ environment_variable.SynapseDevAwsAccountId }}"
  PeerVPCCIDR: 10.11.0.0/16
  PeerRoleName: essentials-VPCPeeringAuthorizerRole-ANWU0AZR9EZ7
