template_path: remote-templates/peer-route-config.yaml
stack_name: peer-vpn-it-services
parameters:
  PeeringConnectionId: pcx-3727c65f
  VpcPrivateRouteTable: rtb-49b14935
  VpcPublicRouteTable: rtb-d3b64eaf
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/peer-route-config.yaml ./remote-templates/peer-route-config.yaml"
