Description: Setup service accounts
AWSTemplateFormatVersion: 2010-09-09
Resources:
  # !! IMPORTANT !! - AWS API will refuse to remove users that have attached resources.
  # Therefore you must do the following before deleting them from this file:
  # 1. Detach or remove the following user resources: login profile, attached
  #    MFA device, access-keys, ssh-keys, and policies.
  # 2. Detach the user from all groups.
  CfnDeployerServiceUser:
    Type: 'AWS::IAM::User'
  CfnDeployerServiceUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref CfnDeployerServiceUser
  CfnDeployerServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !GetAtt CfnDeployerServiceUser.Arn
            Action:
              - "sts:AssumeRole"
  CfnDeployerServiceRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "deployer"
      Roles:
        - !Ref CfnDeployerServiceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
            Resource: arn:aws:s3:::*
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - 'Fn::ImportValue': !Sub '${AWS::Region}-bootstrap-CloudformationBucketArn'
              - 'Fn::ImportValue': !Sub '${AWS::Region}-essentials-LambdaArtifactsBucketArn'
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:DeleteObject
            Resource:
              - 'Fn::Join':
                  - ''
                  - - 'Fn::ImportValue': !Sub '${AWS::Region}-bootstrap-CloudformationBucketArn'
                    - '/*'
              - 'Fn::Join':
                  - ''
                  - - 'Fn::ImportValue': !Sub '${AWS::Region}-essentials-LambdaArtifactsBucketArn'
                    - '/*'
Outputs:
  CfnDeployerServiceUser:
    Value: !Ref CfnDeployerServiceUser
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CfnDeployerServiceUser'
  CfnDeployerServiceUserArn:
    Value: !GetAtt CfnDeployerServiceUser.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CfnDeployerServiceUserArn'
  CfnDeployerServiceUserAccessKey:
    Value: !Ref CfnDeployerServiceUserAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CfnDeployerServiceUserAccessKey'
  CfnDeployerServiceUserSecretAccessKey:
    Value: !GetAtt CfnDeployerServiceUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CfnDeployerServiceUserSecretAccessKey'
  CfnDeployerServiceRole:
    Value: !Ref CfnDeployerServiceRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CfnDeployerServiceRole'
  CfnDeployerServiceRoleArn:
    Value: !GetAtt CfnDeployerServiceRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CfnDeployerServiceRoleArn'
