AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template sets up routes from the VPN to a target VPC.
Metadata: {}
Parameters:
  PeerVPCCIDR:
    Description: CIDR of the VPC in the peering account (i.e. 10.17.0.0/16)
    Type: String
  VPCPeeringConnectionId:
    Description: The VPC peering connection ID
    Type: String
Resources:
  # Configure the VPN to VPC routes
  SophosQueenRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !ImportValue "us-east-1-sophos-utm-QueenRouteTable"
      DestinationCidrBlock: !Ref "PeerVPCCIDR"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionId
  SophosSwarmRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !ImportValue "us-east-1-sophos-utm-SwarmRouteTable"
      DestinationCidrBlock: !Ref "PeerVPCCIDR"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionId

