# Template source https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/solutions/VPCPeering/VPCPeer.json
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template create a lambda function and use it to accept a cross account
  VPC Peer request. It then sets up routes from the VPN to the target VPC.
Metadata: {}
Parameters:
  PeerVPCCIDR:
    Description: CIDR of the VPC in the peering account (i.e. 10.17.0.0/16)
    Type: String
  VPCPeeringConnectionId:
    Description: The VPC peering connection ID
    Type: String
Resources:
  # Configure the VPN to VPC routes
  SophosQueenRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !ImportValue "us-east-1-sophos-utm-QueenRouteTable"
      DestinationCidrBlock: !Ref "PeerVPCCIDR"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionId
  SophosSwarmRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !ImportValue "us-east-1-sophos-utm-SwarmRouteTable"
      DestinationCidrBlock: !Ref "PeerVPCCIDR"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionId
